channels:
  - defaults
dependencies:
  - python=3.6.7
  - pip=19.0.3
  - numpy=1.17.2 # so we get the mkl libs as well
  - pip:
    - pytest==4.6.3
    - pylint==2.3.1
    - flask==1.1.1
    - gunicorn==20.0.4